In [78]:
import pandas as pd

series1 = pd.Series([4.5,7.2,-5.3,3.6])
display(series1)
display(series1[0])
series2 = pd.Series([4.5,7.2,-5.3,3.6],index = ['d','b','a','c'])
display(series2)
display(series2['d'])
display(series2['d':'c'])


0    4.5
1    7.2
2   -5.3
3    3.6
dtype: float64

4.5

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

4.5

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [79]:
#重新排序
display(series2)
display(series2.reindex(['a','b','c','d']))
display(series2.reindex(['a','b']))
series2.values

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

a   -5.3
b    7.2
dtype: float64

array([ 4.5,  7.2, -5.3,  3.6])

In [80]:
import numpy as np
import pandas as pd

series3 = np.arange(9)
display(series3)
display(series3.reshape(3,3))
dataFrame1 = pd.DataFrame(series3.reshape(3,3),index = ['a','b','c'],columns = ["台北","台中","高雄"])
display(dataFrame1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

台北  台中  高雄
a   0   1   2
b   3   4   5
c   6   7   8

In [81]:
display(dataFrame1["台北"])
display(dataFrame1[["台北","台中"]])
display(dataFrame1.iloc[0])
display(dataFrame1.loc['a'])
display(dataFrame1.loc[['a','b']])

a    0
b    3
c    6
Name: 台北, dtype: int64

台北  台中
a   0   1
b   3   4
c   6   7

台北    0
台中    1
高雄    2
Name: a, dtype: int64

台北    0
台中    1
高雄    2
Name: a, dtype: int64

台北  台中  高雄
a   0   1   2
b   3   4   5

In [82]:
import pandas as pd

dataFrame2 = pd.read_csv("各鄉鎮市區人口密度.csv",skiprows = 1)
display(dataFrame2)

統計年                                                區域別   年底人口數  \
0    106.0                                             新北市板橋區  551480   
1    106.0                                             新北市三重區  387484   
2    106.0                                             新北市中和區  413590   
3    106.0                                             新北市永和區  222585   
4    106.0                                             新北市新莊區  416524   
..     ...                                                ...     ...   
370    NaN                                                NaN     NaN   
371    NaN                           說明：1.人口密度係指每單位土地面積內之人口數。     NaN   
372    NaN  2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里)     NaN   
373    NaN           ，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。     NaN   
374    NaN           3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。     NaN   

        土地面積   人口密度  
0    23.1373  23835  
1    16.3170  23747  
2    20.1440  20532  
3     5.7138  38956  
4    19.7383  21102  
..       ...    ...  
370      NaN    NaN  
371      NaN    NaN  
372      NaN    NaN  
373      NaN    NaN  
374      NaN    NaN  

[375 rows x 5 columns]

In [83]:
display(dataFrame2.index)
display(dataFrame2.columns)


RangeIndex(start=0, stop=375, step=1)

Index(['統計年', '區域別', '年底人口數', '土地面積', '人口密度'], dtype='object')

In [84]:
dataFrame3 = dataFrame2.drop(index = [370,371,372,373,374])
dataFrame3

統計年     區域別   年底人口數     土地面積   人口密度
0    106.0  新北市板橋區  551480  23.1373  23835
1    106.0  新北市三重區  387484  16.3170  23747
2    106.0  新北市中和區  413590  20.1440  20532
3    106.0  新北市永和區  222585   5.7138  38956
4    106.0  新北市新莊區  416524  19.7383  21102
..     ...     ...     ...      ...    ...
365  106.0  連江縣北竿鄉    2360   9.9000    238
366  106.0  連江縣莒光鄉    1624   4.7000    346
367  106.0  連江縣東引鄉    1352   3.8000    356
368  106.0    東沙群島      …    2.3800     … 
369  106.0    南沙群島      …    0.5045     … 

[370 rows x 5 columns]

In [85]:
dataFrame4 = dataFrame3.reindex(columns = ["區域別","年底人口數","土地面積","人口密度"])
dataFrame4

區域別   年底人口數     土地面積   人口密度
0    新北市板橋區  551480  23.1373  23835
1    新北市三重區  387484  16.3170  23747
2    新北市中和區  413590  20.1440  20532
3    新北市永和區  222585   5.7138  38956
4    新北市新莊區  416524  19.7383  21102
..      ...     ...      ...    ...
365  連江縣北竿鄉    2360   9.9000    238
366  連江縣莒光鄉    1624   4.7000    346
367  連江縣東引鄉    1352   3.8000    356
368    東沙群島      …    2.3800     … 
369    南沙群島      …    0.5045     … 

[370 rows x 4 columns]

In [86]:
dataFrame4.index = dataFrame4["區域別"]
dataFrame5 = dataFrame4.drop(columns = ["區域別"])
display(dataFrame5)
dataFrame5.loc[["新北市中和區","新北市永和區","新北市新莊區"]]

年底人口數     土地面積   人口密度
區域別                           
新北市板橋區  551480  23.1373  23835
新北市三重區  387484  16.3170  23747
新北市中和區  413590  20.1440  20532
新北市永和區  222585   5.7138  38956
新北市新莊區  416524  19.7383  21102
...        ...      ...    ...
連江縣北竿鄉    2360   9.9000    238
連江縣莒光鄉    1624   4.7000    346
連江縣東引鄉    1352   3.8000    356
東沙群島        …    2.3800     … 
南沙群島        …    0.5045     … 

[370 rows x 3 columns]

年底人口數     土地面積   人口密度
區域別                           
新北市中和區  413590  20.1440  20532
新北市永和區  222585   5.7138  38956
新北市新莊區  416524  19.7383  21102

In [87]:
def toInt(value:str) -> int:
    try:
        newValue = eval(value)
    except:
        newValue = 0
    return newValue

dataFrame3.info()
dataFrame3["年底人口數"] = dataFrame3["年底人口數"].map(toInt)
dataFrame3["人口密度"] = dataFrame3["人口密度"].map(toInt)
display(dataFrame3)
dataFrame3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   統計年     370 non-null    float64
 1   區域別     370 non-null    object 
 2   年底人口數   370 non-null    object 
 3   土地面積    370 non-null    float64
 4   人口密度    370 non-null    object 
dtypes: float64(2), object(3)
memory usage: 14.6+ KB


統計年     區域別   年底人口數     土地面積   人口密度
0    106.0  新北市板橋區  551480  23.1373  23835
1    106.0  新北市三重區  387484  16.3170  23747
2    106.0  新北市中和區  413590  20.1440  20532
3    106.0  新北市永和區  222585   5.7138  38956
4    106.0  新北市新莊區  416524  19.7383  21102
..     ...     ...     ...      ...    ...
365  106.0  連江縣北竿鄉    2360   9.9000    238
366  106.0  連江縣莒光鄉    1624   4.7000    346
367  106.0  連江縣東引鄉    1352   3.8000    356
368  106.0    東沙群島       0   2.3800      0
369  106.0    南沙群島       0   0.5045      0

[370 rows x 5 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   統計年     370 non-null    float64
 1   區域別     370 non-null    object 
 2   年底人口數   370 non-null    int64  
 3   土地面積    370 non-null    float64
 4   人口密度    370 non-null    int64  
dtypes: float64(2), int64(2), object(1)
memory usage: 14.6+ KB


In [92]:
dataFrame4 = dataFrame3.iloc[:5]
display(dataFrame4)
display(dataFrame4["年底人口數"] > 400000)
dataFrame4[dataFrame4["年底人口數"] > 400000]

統計年     區域別   年底人口數     土地面積   人口密度
0  106.0  新北市板橋區  551480  23.1373  23835
1  106.0  新北市三重區  387484  16.3170  23747
2  106.0  新北市中和區  413590  20.1440  20532
3  106.0  新北市永和區  222585   5.7138  38956
4  106.0  新北市新莊區  416524  19.7383  21102

0     True
1    False
2     True
3    False
4     True
Name: 年底人口數, dtype: bool

統計年     區域別   年底人口數     土地面積   人口密度
0  106.0  新北市板橋區  551480  23.1373  23835
2  106.0  新北市中和區  413590  20.1440  20532
4  106.0  新北市新莊區  416524  19.7383  21102

In [95]:
display(dataFrame3["年底人口數"].max())
display(dataFrame3["年底人口數"].min())
display(dataFrame3["年底人口數"].mean())

551480

0

63706.01891891892

In [93]:
#作業
import pandas as pd

dataFrame1 = pd.read_csv("上市公司資料.csv")
dataFrame2 = dataFrame1.reindex(columns = ["產業別","營業收入-當月營收","營業收入-上月營收"])
dataFrame2.columns = ["產業別","當月營收","上月營收"]
# dataFrame2.index = dataFrame1["公司名稱"]
display(dataFrame2)

產業別     當月營收     上月營收
0    水泥工業  7069221  7864622
1    水泥工業   390053   326691
2    水泥工業   478276   557403
3    水泥工業   176935   134470
4    食品工業    38696    29503
..    ...      ...      ...
834    其他   352730   349111
835  觀光事業   212912   197756
836    其他   179660   231139
837    其他    81881    85625
838  鋼鐵工業   757968   651699

[839 rows x 3 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 839 entries, 0 to 838
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   產業別     839 non-null    object
 1   當月營收    839 non-null    int64 
 2   上月營收    839 non-null    int64 
dtypes: int64(2), object(1)
memory usage: 19.8+ KB
